# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "0-0.im"
baseURL = "https://0-0.im"
theme = "FixIt"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
languageName = "简体中文"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = false
relativeURLs = false
buildDrafts = false
summaryLength = 0
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
