# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
identifier = "archives"
parent = ""
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "归档"
url = "/archives/"
# title will be shown when you hover on this menu link
title = ""
weight = 1
# FixIt 0.2.14 | NEW add user-defined content to menu items
[main.params]
# add css class to a specific menu item
class = ""
# whether set as a draft menu item whose function is similar to a draft post/page
draft = false
# FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
icon = "fa-solid fa-archive"
# FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
type = ""


[[main]]
identifier = "categories"
parent = ""
pre = ""
post = ""
name = "分类"
url = "/categories/"
# title = ""
weight = 2
[main.params]
icon = "fa-solid fa-folder-tree"
[[main]]
identifier = "software"
parent = "categories"
pre = ""
post = ""
name = "软件"
url = "/categories/软件/"
title = ""
weight = 1
[main.params]
icon = "fa-solid fa-layer-group"
[[main]]
identifier = "services"
parent = "categories"
pre = ""
post = ""
name = "服务"
url = "/categories/服务/"
title = ""
weight = 1
[main.params]
icon = "fa-solid fa-server"
[[main]]
identifier = "Linux"
parent = "categories"
pre = ""
post = ""
name = "Linux"
url = "/categories/linux/"
title = ""
weight = 0
[main.params]
icon = "fa-brands fa-linux"
[[main]]
identifier = "Windows"
parent = "categories"
pre = ""
post = ""
name = "Windows"
url = "/categories/windows/"
title = ""
weight = 0
[main.params]
icon = "fa-brands fa-windows"


[[main]]
identifier = "tags"
parent = ""
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 3
[main.params]
icon = "fa-solid fa-tags"
